### ISSUE TITLE
Noobie question about MSBuildForUnity

### ISSUE THREAD

**Issue by loic-lopez** [microsoft/MSBuildForUnity#44] opened 2019-11-02 16:53 UTC
Hello everyone I wondering if is it possible to use MSBuildForUnity and Fody.

I have created a `.csproj` file under Assets/Scripts/Library

added : 
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Fody" Version="6.0.3"/>
        <PackageReference Include="MethodTimer.Fody" Version="3.1.0"/>
    </ItemGroup>
</Project>
```

But it throws: 

```
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name Library.dll included for the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: Assets/Scripts/Library/bin/Debug/netstandard2.0/Library.dll, Assets/Scripts/Library/obj/Debug/netstandard2.0/Library.dll
```

**In fact I'm looking for a tool that would allow me to use weaving code on unity, like Fody**

Thanks for reply

**Comment by bddckr** [comment] 2019-11-04 10:49
Have a look at https://github.com/ExtendRealityLtd/Malimbe/.

I'd love to kill that project if MSBuildForUnity has a way to allow using Fody directly instead :)

**Comment by loic-lopez** [comment] 2019-11-04 12:15
Thanks for this reference I will try it soon as possible.

Closing this issue.

**Comment by ryantrem** [comment] 2019-11-05 01:33
You should definitely be able to use Fody with MSBuildForUnity. In the case described above by @loic-lopez, the problem is that by default, the build for csproj puts the compiled dll in both the obj directory and the bin directory, and so Unity sees it twice and doesn't know how to handle it. There are a couple ways to deal with this, but the simplest is to put the project in a directory that Unity won't process. To do this, you can either: 

1. Put the csproj in a directory that starts with a `.` (Unity ignores these). Check out the current sample project for this route: https://github.com/microsoft/MSBuildForUnity/tree/master/Source/MSBuildTools.Unity/Assets/Samples
2. Move the csproj outside of the Unity project's Assets directory, and set the <OutputPath> in the csproj to be a directory under Assets. This way, the final outputs (normally in the bin directory) will be pushed into the Unity project.

@andreiborodin is doing a bunch of work on the project generation side that will make this easier. The generated projects ultimately will be used for both consuming dependencies - ProjectReference (MSBuild project) or PackageReference (NuGet package). We'll have more samples demonstrating this soonish.

**Comment by loic-lopez** [comment] 2019-11-05 07:53
Thanks @ryantrem, I will wait for your samples 🥇

**Comment by andreiborodin** [comment] 2019-11-19 05:27
#35 Has just been put in, there are now two samples linked from the main readme:
https://github.com/microsoft/MSBuildForUnity/#msbuildforunity

Tagging for notification. @loic-lopez, @bddckr

**Comment by loic-lopez** [comment] 2019-11-19 08:07
Also in theory I should be able to use the Fody library through this example:

https://github.com/microsoft/MSBuildForUnity/tree/master/Samples/SimpleNuGetDependency.Unity

**Comment by andreiborodin** [comment] 2019-11-19 17:38
> @andreiborodin Thanks, but the two links are broken in the readme.
> 
> https://github.com/microsoft/MSBuildForUnity/blob/master/Samples/SimpleNuGetDependency.Unity/Readme.md
> https://github.com/microsoft/MSBuildForUnity/blob/master/Samples/IntegratedDependencies.Unity/Readme.md

Oh wow, GitHub is case sensitive on that link for "README.md", will update.

**Comment by andreiborodin** [comment] 2019-11-19 17:50
> Also in theory I should be able to use the Fody library through this example:
> https://github.com/microsoft/MSBuildForUnity/tree/master/Samples/SimpleNuGetDependency.Unity
> I would like to do something like that with Fody in a MonoBehaviour:
> public class MyBehaviour : MonoBehaviour
> {
>     [Time]
>     public void MyMethod()
>     {
>         //Some code u are curious how long it takes
>         Console.WriteLine("Hello");
>     }
> }
> Ref: Fody/MethodTimer
> Thanks for your help.

Ok, so I am not very familiar with Fody, however, as I understand it's two NuGet packages and then a special compilation step that replaces default source compilation?

We currently let Unity compile our scripts, however, we in the https://github.com/microsoft/MSBuildForUnity/tree/master/Samples/IntegratedDependencies.Unity sample we do setup C# projects for asmdefs in the repo that reference all the Unity libraries.

I think you can craft a special C# project based on the [AsmDef generated projects](https://github.com/microsoft/MSBuildForUnity/blob/master/Samples/IntegratedDependencies.Unity/Assets/Assembly-CSharp.msb4u.csproj). It references generated .g.props and g.targets that will be geneerated when you open the Editor. Those generated props/targets reference Unity libraries and can allow you to build Unity scripts outside of Unity.

This special crafted project with it's script should be invisible to Unity, so either outside of Assets or in a folder that is prefixed with a dot '.' in the assets folder.

You can then reference that project from Dependencies.msb4u.csproj.

You will need to have Auto Generation Enabled for this, so start with IntegratedDependencies.msb4u sample.

**Comment by loic-lopez** [comment] 2019-11-19 17:54
@andreiborodin yes Fody will weave assemblies after the dll are generated.

I will try the IntegratedDependencies.Unity so.

**Comment by andreiborodin** [comment] 2019-11-19 18:36
So that what I was trying to say in my longer post above. The IntegratedDependencies.Unity generates the C# Projects and Solution that can be used to build compiled Unity binaries outside of Unity editor.

So, you can do the same for your code, and have it live outside of Unity, and as long as it references the same imports as the generated props, it should build.

I will see if I can find sometime and hack up a C# project for you.

**Comment by andreiborodin** [comment] 2019-11-20 05:21
I managed to hack up some stuff quickly, @loic-lopez  I have a PR for you here: #61 

There are two very similar C# projects that are of interest to you:
- CustomUnityBuild
- CustomUnityBuild.Player

You can find notes in them that I added, they are prefixed "anborod NOTE::"

They both reference the same source file under .src folder (invisible to Unity) which is in fact a Unity MonoBehaviour.

These projects get build by Unity, and then they rely on current Editor's very own DLLs to build against and place the output into Unity.

Caveat! I had to check-in the meta files, as I couldn't properly hook into our metafilegenerator (there is a task on us to reconcile this). There are two being produced.

Additionally, I have to have two projects to build current platform editor version and player version, we will support a better way in the future.

Finally, any NuGet referenced by these projects will be brought in regardless if any other project file in Unity references the same NuGet package already.

Hopefully this get's you started.

**Comment by loic-lopez** [comment] 2019-11-20 07:47
@andreiborodin thanks for your help I will try out your PR as soon as possible!

**Comment by loic-lopez** [comment] 2019-11-20 08:24
@andreiborodin I have encountered multiple issue when building the `IntegratedDependencies.Unity` on Unity 2018.4.12
example:

```
MSBuildForUnity\Samples\IntegratedDependencies.Unity\Assets\CustomUnityBuild\CustomUnityBuild.csproj(54,3): error MSB4019: The imported project "C:\.InEditor.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk

MSBuildForUnity\Samples\IntegratedDependencies.Unity\Assets\CustomUnityBuild\CustomUnityBuild.Player.csproj(64,3): error MSB4019: The imported project "C:\.Player.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

MSBuildForUnity\Samples\IntegratedDependencies.Unity\Assets\Dependencies.msb4u.csproj(33,3): error MSB4019: The imported project "C:\Dependencies.msb4u.g.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

Sorry if I miss something I'm very not familiar with msbuild.

**Comment by andreiborodin** [comment] 2019-11-20 17:08
Did you try opening the Unity solution first?

**Comment by andreiborodin** [comment] 2019-11-21 04:08
Also, there was a bug that I fixed in master, so I updated the branch.

**Comment by loic-lopez** [comment] 2019-11-21 10:11
@andreiborodin Hi again, so I pulled your update and there is other issues on Unity startup: 
```
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Build.Unity.ProjectGeneration.Exporters.TemplatedProjectExporter.ProcessPlatformTemplate (Microsoft.Build.Unity.ProjectGeneration.Templates.ITemplatePart rootPart, Microsoft.Build.Unity.ProjectGeneration.Templates.TemplateReplacementSet rootReplacementSet, System.String platformName, System.String configuration, UnityEditor.BuildTarget buildTarget, Microsoft.Build.Unity.ProjectGeneration.TargetFramework targetFramework, System.Collections.Generic.IEnumerable`1[T] references, System.Collections.Generic.IEnumerable`1[T] defines, System.Collections.Generic.HashSet`1[System.String][] priorToCheck) [0x000da] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\Exporters\TemplatedProjectExporter.cs:534 
  at Microsoft.Build.Unity.ProjectGeneration.Exporters.TemplatedProjectExporter.ExportPlatformPropsFile (Microsoft.Build.Unity.ProjectGeneration.CompilationPlatformInfo platform, System.Boolean inEditorConfiguration) [0x000a2] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\Exporters\TemplatedProjectExporter.cs:504 
  at Microsoft.Build.Unity.ProjectGeneration.MSBuildTools.ExportCoreUnityPropFiles () [0x00029] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\MSBuildTools.cs:169 
  at Microsoft.Build.Unity.ProjectGeneration.MSBuildTools.RegenerateEverything (System.Boolean reparseUnityData) [0x000da] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\MSBuildTools.cs:206 
  at Microsoft.Build.Unity.ProjectGeneration.MSBuildTools.RunCoreAutoGenerate (System.Boolean skipTokenFileCheck) [0x0003b] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\MSBuildTools.cs:154 
  at Microsoft.Build.Unity.ProjectGeneration.MSBuildTools..cctor () [0x0006f] in C:\Users\LoicL\Desktop\MSBuildForUnity\Source\MSBuildTools.Unity\Packages\com.microsoft.msbuildforunity\Editor\ProjectGenerator\Scripts\MSBuildTools.cs:138 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
```

```
Win32Exception: ApplicationName='dotnet', CommandLine='msbuild CustomUnityBuild.csproj -restore  -v:minimal -p:NuGetInteractive=true  -t:Build -p:Configuration=Release -nologo', CurrentDirectory='C:\Users\LoicL\Desktop\MSBuildForUnity\Samples\IntegratedDependencies.Unity\Assets\CustomUnityBuild', Native error= Le fichier spécifié est introuvable.

System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) (at <9f8c4786222746238eb929db40bf8dd1>:0)
System.Diagnostics.Process.Start () (at <9f8c4786222746238eb929db40bf8dd1>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
Microsoft.Build.Unity.MSBuildProjectBuilder+<ExecuteMSBuildAsync>d__17.MoveNext () (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:452)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Microsoft.Build.Unity.MSBuildProjectBuilder+<BuildProjectAsync>d__16.MoveNext () (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:396)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Microsoft.Build.Unity.MSBuildProjectBuilder+<BuildProjectsAsync>d__10.MoveNext () (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:289)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <599589bf4ce248909b8a14cbe4a2034e>:0)
Microsoft.Build.Unity.MSBuildProjectBuilder.BuildProjects (System.Collections.Generic.IReadOnlyCollection`1[T] msBuildProjectReferences, System.String profile, System.String additionalArguments) (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:203)
Microsoft.Build.Unity.MSBuildProjectBuilder+BuildOnLoad.BuildAllAutoBuiltProjects () (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilderEditor.cs:109)
Microsoft.Build.Unity.MSBuildProjectBuilder+BuildOnLoad+<>c.<.cctor>g__OnUpdate|0_0 () (at C:/Users/LoicL/Desktop/MSBuildForUnity/Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilderEditor.cs:93)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)
```

These issues are also displayed when I try to `Build All Projects` in the MSBuild menu.

**Comment by loic-lopez** [comment] 2019-11-21 11:02
So after compiling mannually the CustomUnityBuild.csproj I was able to add Fody and MethodTimer.Fody to the deps:


```cs
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using MethodTimer;
using UnityEngine;

public class ExternalMonoBehaviour : MonoBehaviour
{
    // Start is called before the first frame update
    [Time]
    void Start()
    {
        Debug.Log(typeof(ExternalMonoBehaviour).BaseType.FullName);
    }
}

public static class MethodTimeLogger
{
    public static void Log(MethodBase methodBase, long milliseconds, string message)
    {
        Debug.Log("FROM WEAVING");
    }
}
```

And the console print: 
![image](https://user-images.githubusercontent.com/17724398/69332285-a39e4200-0c56-11ea-8402-c26395da5a98.png)

So Fody is weaving the assembly pretty well!

**Comment by andreiborodin** [comment] 2019-11-21 17:07
Awesome of the result, but could you tell me if you are still able to repro the Unity editor issues. If you check-in your changes to the proj file, do a git clean, and then open Unity again, what do you get?

I would like to work out those kinks.

**Comment by loic-lopez** [comment] 2019-11-21 17:10
@andreiborodin I always use the Unity editor, and also I have pulled the latest change on the custom branch.

**Comment by andreiborodin** [comment] 2019-11-21 17:15
Ok, well just to be pedantic I will try that again, but I have been doing various testing and not seeing anything regarding failing to parse the template.

I wonder if there is something about my context that is different from yours, one you said you re-installed VS and that changed the behavior.

I appreciate you trying this and finding issues, it helps me fix the few issues.

**Comment by loic-lopez** [comment] 2019-11-21 17:17
Thanks you again for helping me to integrate Fody.

**Comment by andreiborodin** [comment] 2019-11-22 00:26
Closing this issue, opened another issue to track supporting this concrete scenario.

**Closed by andreiborodin** 2019-11-22 00:26 UTC
